getsentry/publish

.github/workflows/publish.yml
This PR changes how we publish from a subfolder. Previously, we moved the contents of the subfolder to `GITHUB_WORKSPACE` as the `craft` action (image) could not work inside subfolders. This also came at the cost of losing the `.git` folder at the top level for local `git` operations.
This patch checks out the target repo under `__repo__` and then overrides the `entrypoint` and `args` of the Craft Action to run it inside the subfolder.
=> ref(publish): Simplify publish from subfolder

.github/workflows/publish.yml
We set this to `Debug` now. See also: getsentry/craft#251.
=> ref(logging): Add CRAFT_LOG_LEVEL setting through secrets

.github/workflows/publish.yml
According to [this search](https://github.com/search?l=YAML&p=1&q=org%3Agetsentry+zeus&type=Code) there are no projects that use Zeus _and_ this repo. We can also remove Zeus support from Craft after this.
=> ref(publish): Remove ZEUS_TOKEN

src/publish/__tests__/fail.js, src/publish/fail.js
Fix up to #334 where we changed the main working path for the repo and Craft
=> fix(craft): Fix broken state saving on fail

src/publish/__tests__/fail.js, src/publish/fail.js
Follow up to #367. See https://docs.github.com/en/rest/reference/actions#get-a-job-for-a-workflow-run
=> fix(publish): Turns out we need to use the Job ID

src/publish/__tests__/fail.js, src/publish/fail.js
Reverts getsentry/publish#372
@jan-auer [reported on Slack](https://sentry.slack.com/archives/C01C205FUAE/p1623406421001400):
>@BYK looks like there's a small issue when reporting a failed publish:
>https://github.com/getsentry/publish/runs/2801793195?check_suite_focus=true#step:9:15
=> Revert "fix(publish): Turns out we need to use the Job ID"

.github/workflows/calver.yml
We bump our month part of the releases on or after 15th of every month. The auto calver mechanism here was not aware of that and now it is with this patch.
=> fix(calver): Fix auto calver as we do releases on 15th

.github/workflows/publish.yml
This got obsolete as getsentry/craft#281 has landed now.
=> fix(cocoapods): Remove COCOAPODS_ALLOW_ROOT=1

.github/workflows/publish.yml
To unblock this release: https://github.com/getsentry/publish/runs/3561537707
The secret has already been defined in the repo so rerun should complete the release
=> add nuget env var

.github/workflows/publish.yml
Newer craft releases upload broken release artifacts to github.
=> fix: pin craft to 031aad308fd2a4f1b96f82dd8f881456bd8fea44

.github/workflows/publish.yml
Craft 0.25.3 is out with a fix so we no longer need this pinning.
This reverts commit c2aecd0d1e3c0345ef79444ee908c02d84485eb1.
=> Revert "fix: pin craft to 031aad308fd2a4f1b96f82dd8f881456bd8fea44 (#577)"

.github/workflows/publish.yml, package.json, src/publish/__tests__/fail.js, src/publish/fail.js, src/publish/start.js, src/publish/success.js, src/sentry.js, yarn.lock
Adding Sentry SDK so we can track crash fail rate overall our releases
=> chore: track crash fail rate

.github/workflows/publish.yml
This is required in order for installed deps to be picked up correctly.
=> ref: Bump github-script action to v5

src/publish/__tests__/fail.js, src/publish/fail.js, src/publish/success.js
Add session tracking to enable calculation of release health / crash-free rate in Sentry releases tab.
=> chore: add session tracking

src/publish/__tests__/fail.js, src/publish/fail.js, src/publish/success.js
With the latest, `6.17.5` version of SDK, we don't need to use `getCurrentHub` for creating `Session` object.
=> ref: Simplify Sentry SDK code

.github/workflows/publish.yml
This PR is a prerequisite for https://github.com/getsentry/craft/pull/346
To generate a valid secret key:
```terminal
gpg --quick-generate-key bot@sentry.io
gpg --armor --export-secret-keys bot@sentry.io | pbcopy
```
Paste copied key as `GPG_SECRET_KEY` and entered password as `GPG_PASSPHRASE`.
=> feat: Add GPG_SECRET_KEY and GPG_PASSPHRASE secrets for craft

.github/workflows/publish.yml
For Dart and Flutter via `pub-dev` target.
=> feat: Add PUBDEV_ACCESS_TOKEN and PUBDEV_REFRESH_TOKEN secrets for craft

.github/workflows/publish.yml, src/publish/__tests__/fail.js, src/publish/__tests__/inputs.js, src/publish/inputs.js
See https://github.com/getsentry/craft/pull/355 for more details.
=> feat: Allow for passing custom merge target

.github/workflows/retract.yml, README.md, src/publish/__tests__/inputs.js, src/publish/inputs.js, src/publish/retract.js
This will only comment and close the original issue.
It will *not* cancel any running actions nor will it remove the release branch.
This is to keep it simple for now, not leave actions in the middle of some random state, and to not accidentally remove someone's release branch if it was created by hand.
Closes https://github.com/getsentry/publish/pull/882/
=> feat: Allow for retracting a request release

.github/workflows/publish.yml, src/publish/__tests__/fail.js, src/publish/__tests__/update-targets.js, src/publish/fail.js, src/publish/update-targets.js
GH Actions timeouts are not treated as `failed` but rather `canceled`. Because of that, release attempts that failed after some targets already succeeded were not updated with appropriate checkboxes.
This PR extracts targets update logic to a separate action, and triggers it in case of failure *and* canceled runs.
=> ref: Update targets on canceled runs too

.github/workflows/publish.yml
Default 6 hours is a huge overkill. The only target that can take time even remotely close to this is `sentry-java` with its `maven` target which retries for 30 minutes.
This allows us for faster retriggers in case something goes wrong with (usually) gh artifacts upload, without the assistance of someone with admin permissions to cancel runs.
=> ref: Set timeout-minutes to 60 instead of default 360

.github/workflows/calver.yml
https://github.blog/changelog/2022-04-25-git-io-deprecation/
=> git.io is going away very soon

.github/workflows/publish.yml
We can either:
- lock the major
- update the code
- remove this feature completely (counting failed/successful deploys) (I'd go with this one tbh)
For now locking is quickest, so we can unlock the deploys.
ref: https://github.com/getsentry/publish/runs/6813933024?check_suite_focus=true#step:13:24
=> deps: Lock @sentry/node to v6

.github/workflows/retract.yml
In https://github.com/getsentry/publish/pull/1342 we merged in changes that converted `Parse and set inputs` step to use a node script instead of a inline script. This needs to be also done for the retract action, which is what this PR does. 
This is blocking retracting https://github.com/getsentry/publish/issues/1358, which is needed to unblock a backport bug fix!
=> fix(retract): Use node script for input.js

.gitignore, src/libs/__tests__/github.js, src/libs/github.js, src/publish/post-result.js, src/publish/post-workflow-details.js, src/publish/retract.js, src/publish/update-issue.js
Changes output from:
To the following:
Should this ever happen again in the future, the warning should highlight the issue quickly.
=> Throw a useful error when GITHUB_TOKEN is missing

.github/workflows/publish.yml
We had a few publish [runs](https://github.com/getsentry/publish/actions) for the sentry android gradle plugin cancelled because maven central (hosting for java packages) is recently very slow https://status.maven.org/. Also opened a PR to craft to increase the deadline for releasing to Maven to 60min. https://github.com/getsentry/craft/pull/450
=> chore: Change timeout to 90 minutes

.github/workflows/publish.yml
Apply workaround mentioned in https://github.com/actions/runner/issues/2033
To hopefully workaround:
```
Error:  fatal: detected dubious ownership in repository at '/github/workspace/__repo__'
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace/__repo__
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace/__repo__
```
https://github.com/getsentry/publish/actions/runs/4088671361/jobs/7050581556#step:10:47
Note: https://github.com/getsentry/craft/pull/455 did not work.
@asottile-sentry
=> Workaround git safe.directory

.github/workflows/auto-approve.yml
This is an aux dependency of sentry-kafka-schemas
=> fix: Add json-schema-diff to auto-approve list

.github/workflows/auto-approve.yml
From the README:
> Internal dependencies such as arroyo can be published with an auto approval. The reasoning here is that the bump of the dependency requires an explicit approval again in Sentry proper.
This is true for the relay python library IMO.
https://github.com/getsentry/publish#approvals
=> feat: Auto-approve releases of relay library

.github/workflows/auto-approve.yml
It's an internal Rust package we use for reporting metrics
=> ref: Auto-approve statsdproxy

.github/workflows/publish.yml
This PR adds a step to the `publish.yml` workflow that determines which branch of the target repo should be checked out.
The checked out branch will be the one where craft takes its config from. 
By default, we always check out the target repo's default branch.
ref #3441
=> feat(publish): Add allowlist for branches to take craft config from

.github/workflows/publish.yml
[Looks like](https://github.com/getsentry/publish/actions/runs/7933357899/job/21661937057#step:9:1) I didn't set the output value in the target repo checkout branch step correctly. This PR (hopefully) fixes that.
=> fix(publish): Set output value target-repo-branch correctly

.github/workflows/publish.yml
This PR opts the `sentry-javascript` repo into checking out specific merge target branches and hence taking the craft config from there for our two branches we release from `v7` - the branch we release 7.x versions from.
=> ref(publish): Add `sentry-javascript/v7` branch to `target-repo-branch` step

.github/workflows/publish.yml
This PR adds the `master` branch to the allowed branches we can take the craft config file from in `sentry-javascript`.
IMHO we should allow taking the config from `master` as well as from `v7` (as done in #3467):
* Our repo's default branch is `develop` while we release from `master` (more information on our [gitflow approach](https://github.com/getsentry/sentry-javascript/blob/develop/docs/gitflow.md)). So there is a chance that the craft config on `develop` is not aligned with the config on `master`, for instance in the case where the config is changed while a release is still in progress.
* I'd like to avoid using two different strategies of obtaining the craft config (i.e. once via the new opt in mechanism, once in the default way), which 1. increases consistency and 2. makes it …
=> ref(publish): Add `sentry-javascript/master` branch to `target-repo-branch` step

.github/workflows/auto-approve.yml
https://github.com/getsentry/status-page-list is a library we extracted out from the sentry frontend. It can be auto approved.
=> feat: Add `status-page-list` to auto-approve

.github/workflows/auto-approve.yml
this package helps us monitor flakes in jest runs and has been dead for a bit
=> chore: add jest-sentry-environment to auto-approve

.github/workflows/publish.yml
Adds the `1.x` branch of the `sentry-wizard` repo to be one of the branches where we can take the craft config from. The config diverged between 1.x and 3.x (latest) and we need to cut a 1.x release. So I'd like to opt this branch into the mechanism we set up for the JS SDK repo.
=> ref(publish): Add `sentry-wizard/1.x` branch to `target-repo-branch` step

.github/workflows/auto-approve.yml
This adds https://github.com/getsentry/infra-event-notifier to the publish auto-approve list
=> add `infra-event-notifier` to auto-approve list

.github/workflows/auto-approve.yml
This repository will eventually contains shared protobuf schemas and generated bindings for rust/python/go. The packages produced from this repository will be used in production applications to facilitate cross-application messaging.
=> chore: Add sentry-protos to the auto-approve list

.github/workflows/auto-approve.yml
sentry-infra-tools repository is going to have tools used by sentry SRE to manage the infrastructure. It does not require elevated privileges to be released.
=> chore(approve): Add sentry-infra-tools to auto approve list

.github/workflows/auto-approve.yml
This PR adds sentry-forked-jsonnet to the auto-approve list
=> chore: Add sentry-forked-jsonnet to auto-approve

.github/workflows/publish.yml
Adds the `v8` branch to the "allowlist" for branch specific craft configs.
We are removing 2 packages in v9 and want to be able to still cut releaseses for v8, meaning we need to have different craft configs.
=> meta: Allowlist craft config from `v8` branch in `getsentry/sentry-javascript`

.github/workflows/publish.yml
> If owner is set and repositories is empty, access will be scoped to all repositories in the provided repository owner's installation. If owner and repositories are empty, access will be scoped to only the current repository.
(https://github.com/actions/create-github-app-token?tab=readme-ov-file#repositories)
We need the GitHub app to have access not only to the `publish` repo, but also the target repo where we are publishing to
=> fix(publish): Fix permission scope for auth token

.github/workflows/auto-approve.yml
This adds https://github.com/getsentry/streams to the auto-approve list
=> add  repo to auto-approve list

.github/workflows/auto-approve.yml
Since `sentry_streams` is a package within the `streams` repo my original path was wrong - this should fix
=> fix: actually auto-approve sentry_streams releases

.github/workflows/publish.yml
Migrate from static credentials in `CRAFT_GCS_*` env vars to dynamic credentials via OIDC.
=> fix: switch publish github action to workload identity

.github/workflows/publish.yml
We want to publish a `sentry_sdk_alpha` package version of the `sentry_sdk` package for easier dogfooding.
=> Add an alpha release branch in python sdk.

.github/workflows/retract.yml
It seems like GH changed new lines from \r\n to \n and therefore the retract comment only worked if was added to a comment and the comment didn't contain any other text. This is fixed now by only checking for \n.
As pointed out here https://github.com/getsentry/action-prepare-release/pull/40#issuecomment-2872769352.
=> Fix retract newline check

src/modules/details-from-context.js
Changes the targets parser to be case insensitive so we handle both `x` and `X` as checked-off.
~~Alternatively, we can make the char-class `[ xX]`.~~
Alternatively we can make the entire regex case-insensitive.
This fixes the issue reported here: https://github.com/getsentry/craft/pull/611#issuecomment-3052962738 (second item)
Related failure: https://github.com/getsentry/publish/issues/5882
=> fix(targets): Target parser should accept both `x` and `X`

.github/workflows/publish.yml
Add the `v9` branch to the allowlist for branch specific craft configs.
=> meta: Allowlist craft config from `v9` branch in `getsentry/sentry-javascript`
