.github/workflows/publish.yml
=> fix(publish): Only trigger publish on open issues

.github/workflows/publish.yml
Fixes the issue in #585, see CocoaPods/CocoaPods#6795
=> fix: Add COCOAPODS_ALLOW_ROOT=1 to publish

.github/workflows/calver.yml
https://github.com/getsentry/self-hosted/issues/796
=> Rename onpremise to self-hosted

src/publish/__tests__/fail.js, src/publish/fail.js, src/publish/start.js, src/publish/success.js
Per https://github.com/actions/github-script#breaking-changes-in-v5
=> fix: Use github.rest namespace for calling octokit

README.md
As seen in https://github.com/getsentry/publish/pull/838/
=> Update README with steps for adding Merge Target option

README.md
Free internet points for merging @chadwhitacre
=> docs: Correctly indent merge target code block to get auto numeration

.github/workflows/publish.yml, package.json, src/modules/__tests__/details-from-context.js, src/modules/details-from-context.js, src/publish/inputs.js, yarn.lock
NOTE: This change also adds `test:watch` to the npm scripts.
=> Switch inputs.js to a node script

.github/workflows/publish.yml, src/modules/__tests__/post-workflow-details.js, src/modules/post-workflow-details.js, src/publish/post-workflow-details.js
=> Switch start.js to a node script

.github/workflows/publish.yml, src/modules/__tests__/update-issue.js, src/modules/update-issue.js, src/publish/update-issue.js
=> Switch update-issue to node script

.github/workflows/retract.yml
=> install yarn dependencies for retract

.github/workflows/retract.yml, src/modules/__tests__/retract-release.js, src/modules/retract-release.js, src/publish/retract.js
Tested this on my fork: https://github.com/mattgauntseo-sentry/publish/issues/1#issuecomment-1245945638
=> refactor(retract): Move retract to a node script [DEVINFRA-89]

.github/workflows/publish.yml
Follow-up to #1827, which [did not work](https://github.com/getsentry/publish/issues/1828#issuecomment-1419120956).
=> We use the __repo__ subdir

.github/workflows/publish.yml
Follow-up to #1830, specifically https://github.com/getsentry/publish/pull/1830#discussion_r1097455282.
=> I guess we need this after all

yarn.lock
=> ref: upgrade jest to appease dependabot

.github/workflows/publish.yml
Reverts getsentry/publish#1834
=> Revert "ref: invoke docker directly to publish"

.github/workflows/publish.yml
Reverts getsentry/publish#1844
=> Revert "ref: override HOME this way instead?"

.github/workflows/auto-approve.yml
https://github.com/getsentry/sentry-redis-tools
=> feat: Auto-approve releases of sentry-redis-tools

.github/workflows/auto-approve.yml
The snuba-sdk is an internal library meant for interfacing with Snuba.
=> ref: Add snuba-sdk to auto approve list

.github/workflows/auto-approve.yml
https://github.com/getsentry/devenv
=> Add auto-approve for devenv

.github/workflows/publish.yml
=> ref: write targets json to subdir-specific path

.github/workflows/auto-approve.yml
adding `sentry-release-bot[bot]` to the allowed actor list
=> fix(auto-approve): Trigger auto approve for sentry-release bot

src/publish/update-issue.js
We had a faulty import introduced by #5026 that caused failures: https://github.com/getsentry/publish/actions/runs/13260007010/job/37014212448
No typescript/linting :sob:
=> fix: Fix faulty import

.github/workflows/test.yml
=> use ubuntu-latest for tests
